"""Seed catalog transcribed from the GlobeTrotter Indian Destinations dataset.

Each city has 10 activities (name, price_per_person) and 10 hotels
(name, tier, price_per_night). Prices are in INR.
"""

SEED_CITIES = [
    {
        "id": 1, "name": "Mumbai", "state": "Maharashtra",
        "activities": [
            ("Gateway of India & Taj Palace Walk", 0),
            ("Marine Drive Sunset Promenade Stroll", 0),
            ("Elephanta Caves Ferry & Island Tour", 260),
            ("CSMT Station Heritage Walk", 0),
            ("Dharavi Guided Tour", 750),
            ("Colaba Causeway Shopping & Cafe Trail", 500),
            ("Bandra Bandstand & Celebrity Homes Walk", 0),
            ("Juhu Beach Street Food Experience", 300),
            ("Sanjay Gandhi National Park & Kanheri Caves", 150),
            ("Crawford Market & Spice Trail Walk", 0),
        ],
        "hotels": [
            ("Abode Bombay", "Boutique", 3500),
            ("Gordon House Hotel", "Mid-Range", 5500),
            ("Hotel Marine Plaza", "4-Star", 7500),
            ("Soho House Mumbai", "Boutique Lux", 12000),
            ("ITC Grand Central", "5-Star Lux", 13500),
            ("Trident Nariman Point", "5-Star Lux", 15000),
            ("JW Marriott Mumbai Juhu", "5-Star Lux", 18000),
            ("The St. Regis Mumbai", "Ultra Lux", 21000),
            ("The Oberoi Mumbai", "Ultra Lux", 24000),
            ("The Taj Mahal Palace", "Iconic Lux", 28000),
        ],
    },
    {
        "id": 2, "name": "New Delhi", "state": "Delhi",
        "activities": [
            ("Red Fort & Chandni Chowk Rikshaw Tour", 350),
            ("Qutub Minar & Mehrauli Walk", 50),
            ("Humayun's Tomb Garden Stroll", 50),
            ("India Gate & Rashtrapati Bhavan Walk", 0),
            ("Lotus Temple Visit", 0),
            ("Akshardham Temple & Light Show", 250),
            ("Old Delhi Food Tasting Experience", 600),
            ("National Gallery of Modern Art", 20),
            ("Lodhi Art District Street Art Walk", 0),
            ("Hauz Khas Village & Fort Sunset Exploration", 20),
        ],
        "hotels": [
            ("Bloomrooms @ Janpath", "Budget Bout.", 2800),
            ("Vivanta New Delhi, Dwarka", "4-Star", 5500),
            ("The Claridges New Delhi", "Heritage 5*", 9500),
            ("Shangri-La Eros New Delhi", "5-Star Lux", 11000),
            ("ITC Maurya", "5-Star Lux", 13000),
            ("Taj Mahal, New Delhi", "5-Star Lux", 16000),
            ("The Lodhi", "Boutique Lux", 18500),
            ("The Imperial New Delhi", "Heritage Ultra", 21000),
            ("The Oberoi, New Delhi", "Ultra Lux", 23000),
            ("The Leela Palace New Delhi", "Ultra Lux", 26000),
        ],
    },
    {
        "id": 3, "name": "Jaipur", "state": "Rajasthan",
        "activities": [
            ("Amber Fort Guided Tour", 200),
            ("Hawa Mahal Photography Walk", 50),
            ("City Palace & Jantar Mantar Tour", 500),
            ("Nahargarh Fort Sunset Panorama Visit", 50),
            ("Jaigarh Fort & Cannon Visit", 100),
            ("Johri Bazaar Block Printing Walk", 0),
            ("Jal Mahal Viewpoint Visit", 0),
            ("Albert Hall Museum Night Tour", 100),
            ("Rajasthani Thali Cooking Class", 1200),
            ("Chokhi Dhani Cultural Village Pass", 1000),
        ],
        "hotels": [
            ("Hotel Pearl Palace", "Heritage Bud.", 1800),
            ("Umaid Bhawan Heritage House", "Heritage Mid", 3200),
            ("Shahpura House", "Heritage 4*", 5500),
            ("ITC Rajputana", "5-Star Lux", 9000),
            ("Fairmont Jaipur", "5-Star Resort", 14000),
            ("Taj Jai Mahal Palace", "Heritage 5*", 18000),
            ("Alila Fort Bishangarh", "Heritage Res.", 22000),
            ("SUJAN Rajmahal Palace", "Boutique Lux", 35000),
            ("The Oberoi Rajvilas", "Ultra Lux Res.", 45000),
            ("Rambagh Palace", "Palace Ultra", 55000),
        ],
    },
    {
        "id": 4, "name": "Bengaluru", "state": "Karnataka",
        "activities": [
            ("Lalbagh Botanical Garden Stroll", 30),
            ("Bengaluru Palace Audio Tour", 250),
            ("Cubbon Park Morning Walk", 0),
            ("Commercial Street Shopping", 0),
            ("ISKCON Temple Visit", 0),
            ("Craft Beer & Pub Crawl in Indiranagar", 1500),
            ("Tipu Sultan's Summer Palace Tour", 20),
            ("National Gallery of Modern Art", 20),
            ("Bannerghatta Biological Park Safari", 350),
            ("Nandi Hills Sunrise Day Trip", 100),
        ],
        "hotels": [
            ("Villa 302", "Budget Stay", 2200),
            ("Bloom Hotel - Indiranagar", "Budget Bout.", 3000),
            ("St. Mark's Hotel", "4-Star", 5200),
            ("Grand Mercure Bengaluru", "5-Star", 7500),
            ("ITC Gardenia", "5-Star Lux", 11000),
            ("JW Marriott Hotel Bengaluru", "5-Star Lux", 13500),
            ("Taj West End", "Heritage 5*", 15000),
            ("The Oberoi, Bengaluru", "5-Star Lux", 16500),
            ("The Ritz-Carlton, Bangalore", "Ultra Lux", 18000),
            ("The Leela Palace Bengaluru", "Ultra Lux", 21000),
        ],
    },
    {
        "id": 5, "name": "Varanasi", "state": "Uttar Pradesh",
        "activities": [
            ("Dashashwamedh Ghat Evening Aarti", 0),
            ("Sunrise Ganges Boat Ride", 400),
            ("Kashi Vishwanath Temple Darshan", 0),
            ("Sarnath Pilgrimage & Museum Tour", 50),
            ("Manikarnika & Harishchandra Ghat Walk", 0),
            ("Banarasi Silk Weaving Village Tour", 300),
            ("Street Food Crawl", 250),
            ("BHU & Bharat Kala Bhavan", 20),
            ("Assi Ghat Subah-e-Banaras Yoga", 0),
            ("Ramnagar Fort & Museum Exploration", 150),
        ],
        "hotels": [
            ("Wanderlust Hostel Varanasi", "Hostel/Bud.", 1200),
            ("Ganges Grand", "Budget Hotel", 2500),
            ("Palace On Ganges", "Heritage Bud.", 3800),
            ("Hotel Surya, Kaiser Palace", "Heritage Mid", 4500),
            ("Clarks Varanasi", "4-Star", 6000),
            ("Tree of Life Resort & Spa", "Boutique Res.", 9500),
            ("Radisson Hotel Varanasi", "5-Star", 10000),
            ("The Gateway Hotel Ganges", "5-Star", 12000),
            ("Taj Ganges, Varanasi", "5-Star Lux", 15000),
            ("BrijRama Palace", "Heritage Pal.", 24000),
        ],
    },
    {
        "id": 6, "name": "Udaipur", "state": "Rajasthan",
        "activities": [
            ("City Palace Complex Tour", 400),
            ("Lake Pichola Sunset Boat Cruise", 800),
            ("Jag Mandir Island Palace Visit", 500),
            ("Saheliyon-Ki-Bari Royal Garden Stroll", 20),
            ("Bagore Ki Haveli Folk Dance Show", 100),
            ("Monsoon Palace Hilltop View", 100),
            ("Jagdish Temple Heritage Walk", 0),
            ("Shilpgram Rural Arts Complex Visit", 50),
            ("Fateh Sagar Lake Promenade", 0),
            ("Miniature Painting Workshop", 600),
        ],
        "hotels": [
            ("Hotel Lakend", "Bud. Heritage", 2500),
            ("Jagat Niwas Palace Hotel", "Heritage Bout.", 4800),
            ("Amet Haveli", "Heritage Stay", 6200),
            ("Chundavada Palace", "Heritage Hotel", 7500),
            ("Fateh Garh Resort", "Heritage Res.", 9500),
            ("Trident Udaipur", "5-Star", 14000),
            ("RAAS Devigarh", "Heritage Pal.", 26000),
            ("The Leela Palace Udaipur", "Palace Lux", 42000),
            ("Taj Lake Palace", "Heritage Ultra", 48000),
            ("The Oberoi Udaivilas", "Iconic Ultra", 52000),
        ],
    },
    {
        "id": 7, "name": "Kolkata", "state": "West Bengal",
        "activities": [
            ("Victoria Memorial Hall & Gardens", 50),
            ("Howrah Bridge & Flower Market Walk", 0),
            ("Dakshineswar & Belur Math Ferry Tour", 30),
            ("Park Street Heritage Walk", 0),
            ("Indian Museum Artifacts Tour", 50),
            ("Kumartuli Clay Idol Makers Colony Walk", 0),
            ("Jorasanko Thakurbari (Tagore House)", 20),
            ("College Street & Indian Coffee House", 150),
            ("St. Paul's Cathedral Architecture Tour", 0),
            ("Hooghly River Sunset Heritage Cruise", 400),
        ],
        "hotels": [
            ("Fairlawn Hotel", "Heritage Bud.", 2200),
            ("The Peerless Inn", "3-Star", 3500),
            ("Peerless Hotel Kolkata", "4-Star", 4800),
            ("Swissotel Kolkata", "4-Star", 6500),
            ("The Lalit Great Eastern", "Heritage 5*", 8000),
            ("The Park Kolkata", "Boutique 5*", 9000),
            ("JW Marriott Hotel Kolkata", "5-Star Lux", 11000),
            ("Taj Bengal Kolkata", "5-Star Lux", 13000),
            ("ITC Royal Bengal", "5-Star Lux", 14500),
            ("The Oberoi Grand Kolkata", "Heritage Ultra", 17000),
        ],
    },
    {
        "id": 8, "name": "Kochi", "state": "Kerala",
        "activities": [
            ("Fort Kochi Fishing Nets Viewpoint", 0),
            ("Mattancherry Palace Tour", 10),
            ("Paradesi Synagogue Visit", 10),
            ("Kathakali Dance & Cultural Show", 400),
            ("Kerala Backwaters Day Cruise", 1200),
            ("St. Francis Church & Vasco Square", 0),
            ("Kalaripayattu Martial Arts Show", 400),
            ("Marine Drive Kochi Promenade", 0),
            ("Spice & Tea Tasting Tour", 500),
            ("Willingdon Island Heritage Walk", 0),
        ],
        "hotels": [
            ("Tissa's Inn", "Budget Bout.", 2200),
            ("Casino Hotel Kochi", "3-Star", 3500),
            ("Eighth Bastion - CGH Earth", "Heritage Mid", 5000),
            ("Forte Kochi", "Heritage Bout.", 6800),
            ("Old Harbour Hotel", "Heritage Bout.", 8000),
            ("Fragrant Nature Kochi", "5-Star Bout.", 9000),
            ("Malabar House", "Relais & Chateaux", 12000),
            ("Grand Hyatt Kochi Bolgatty", "5-Star Resort", 13500),
            ("Taj Malabar Resort & Spa", "5-Star Lux", 16000),
            ("Brunton Boatyard - CGH Earth", "Heritage Ultra", 18000),
        ],
    },
    {
        "id": 9, "name": "Hyderabad", "state": "Telangana",
        "activities": [
            ("Charminar Walk & Lad Bazaar Shopping", 25),
            ("Golconda Fort & Light Show", 150),
            ("Chowmahalla Palace Architecture Tour", 100),
            ("Ramoji Film City Full-Day Tour", 1350),
            ("Qutb Shahi Tombs Walk", 50),
            ("Salar Jung Museum Treasures Tour", 50),
            ("Hussain Sagar Lake & Boat Ride", 100),
            ("Hyderabadi Biryani Culinary Tour", 500),
            ("Nehru Zoological Park Safari", 100),
            ("Birla Mandir Hilltop Visit", 0),
        ],
        "hotels": [
            ("Mercure Hyderabad KCP", "3-Star", 3200),
            ("The Park Hyderabad", "Boutique 4*", 4800),
            ("Novotel Convention Centre", "4-Star", 6500),
            ("Oakwood Residence Kapil", "Serviced Apt.", 7200),
            ("Trident Hyderabad", "5-Star", 10500),
            ("Taj Krishna", "5-Star Lux", 11500),
            ("The Westin Hyderabad", "5-Star Lux", 13000),
            ("Park Hyatt Hyderabad", "5-Star Lux", 15000),
            ("ITC Kohenur", "5-Star Lux", 16500),
            ("Taj Falaknuma Palace", "Palace Ultra", 45000),
        ],
    },
    {
        "id": 10, "name": "Goa", "state": "Goa",
        "activities": [
            ("Basilica of Bom Jesus & Se Cathedral", 0),
            ("Fontainhas Latin Quarter Walk", 0),
            ("Mandovi River Sunset Dinner Cruise", 800),
            ("Dudhsagar Waterfalls & Spice Tour", 1800),
            ("Anjuna & Vagator Beach Sunset", 0),
            ("Aguada Fort Historic Walk", 50),
            ("Scuba Diving at Grand Island", 2500),
            ("Panaji Heritage Market Tour", 0),
            ("Palolem Beach Kayaking", 400),
            ("Anjuna Flea Market Experience", 0),
        ],
        "hotels": [
            ("Heritage Village Resort", "3-Star Res.", 3800),
            ("Cidade de Goa - IHCL", "4-Star Res.", 6500),
            ("Postcard Velha", "Boutique Stay", 9000),
            ("Ahilya By The Sea", "Boutique Res.", 12000),
            ("Grand Hyatt Goa", "5-Star Res.", 14000),
            ("Alila Diwa Goa", "5-Star Lux", 15500),
            ("ITC Grand Goa Resort", "5-Star Res.", 17000),
            ("W Goa", "Lifestyle Lux", 19000),
            ("Taj Exotica Resort & Spa", "Ultra Lux Res.", 22000),
            ("The Leela Goa", "Ultra Lux Res.", 25000),
        ],
    },
]
